
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pramod
 */
public class DataProviderSelector extends javax.swing.JFrame {

    /**
     * Creates new form DataProviderSelector
     */
    public DataProviderSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        cmbSelectDatabaseSQLServer = new javax.swing.JComboBox();
        cmbSelectTableSQLServer = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSQLServerPassword = new javax.swing.JTextField();
        txtSQLServerUserName = new javax.swing.JTextField();
        btnContinue1 = new javax.swing.JButton();
        btnContinue2 = new javax.swing.JButton();
        btnConnectSQLServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnContinue3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Password");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Select Data Table");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Click to Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        cmbSelectDatabaseSQLServer.setToolTipText("Select Database");
        cmbSelectDatabaseSQLServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectDatabaseSQLServerActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSelectDatabaseSQLServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 131, -1));

        cmbSelectTableSQLServer.setToolTipText("Select Table");
        cmbSelectTableSQLServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectTableSQLServerActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSelectTableSQLServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 131, -1));

        jLabel4.setText("Select Database");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setText("User Name");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(txtSQLServerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 160, -1));
        getContentPane().add(txtSQLServerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));

        btnContinue1.setText("Choose MySQL");
        btnContinue1.setToolTipText("Click to Continue");
        btnContinue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinue1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btnContinue2.setText("Continue");
        btnContinue2.setToolTipText("Click to Continue");
        btnContinue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinue2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btnConnectSQLServer.setText("Connect");
        btnConnectSQLServer.setToolTipText("Click to Continue");
        btnConnectSQLServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectSQLServerActionPerformed(evt);
            }
        });
        getContentPane().add(btnConnectSQLServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel1.setText("SQL Server");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        btnContinue3.setText("Continue");
        btnContinue3.setToolTipText("Click to Continue");
        btnContinue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinue3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        new Home().setVisible(true);

    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbSelectDatabaseSQLServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectDatabaseSQLServerActionPerformed
        String[] resuslt = new String[1000];

        String databaseName = (String) cmbSelectDatabaseSQLServer.getSelectedItem();
        if (!cmbSelectDatabaseSQLServer.getSelectedItem().equals("")) {
            DataProviderClass dp = new DataProviderClass();
            cmbSelectTableSQLServer.removeAllItems();
            StateManagerClass stm=new StateManagerClass();
            
            try {
                resuslt = dp.selectTableFromSQLServer(databaseName);            
                for (int i = 0; i < resuslt.length; i++) {
                    if (resuslt[i] == null) {
                    } else {
                        cmbSelectTableSQLServer.addItem(resuslt[i]);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please Select Database From ComboBox", "Exception", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_cmbSelectDatabaseSQLServerActionPerformed

    private void cmbSelectTableSQLServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectTableSQLServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectTableSQLServerActionPerformed

    private void btnContinue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinue1ActionPerformed
        setVisible(false);
        new MySQLDatabaseSelector().setVisible(true);
    }//GEN-LAST:event_btnContinue1ActionPerformed

    private void btnContinue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinue2ActionPerformed

    private void btnConnectSQLServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectSQLServerActionPerformed
        /* */
        if (txtSQLServerUserName.getText().equals("") && txtSQLServerPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Insert User Name and Password");
        } else {
            String[] result = new String[100];
            String userName, password;            
            userName = txtSQLServerUserName.getText();
            password = txtSQLServerPassword.getText();        
            StateManagerClass stm=new StateManagerClass();
            stm.setSQLServerPassword(password);
            stm.setSQLServerUserName(userName);
            cmbSelectTableSQLServer.removeAllItems();
            DataProviderClass dpc = new DataProviderClass();
            try {
                result = dpc.selectDatabaseFromSQLServer(userName, password);

                for (int i = 0; i < result.length; i++) {
                    if (result[i] == null) {
                    } else {

                        cmbSelectDatabaseSQLServer.addItem(result[i]);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnConnectSQLServerActionPerformed

    private void btnContinue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinue3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataProviderSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataProviderSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataProviderSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataProviderSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataProviderSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConnectSQLServer;
    private javax.swing.JButton btnContinue1;
    private javax.swing.JButton btnContinue2;
    private javax.swing.JButton btnContinue3;
    private javax.swing.JComboBox cmbSelectDatabaseSQLServer;
    private javax.swing.JComboBox cmbSelectTableSQLServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.ButtonGroup myGroup;
    private javax.swing.JTextField txtSQLServerPassword;
    private javax.swing.JTextField txtSQLServerUserName;
    // End of variables declaration//GEN-END:variables
}
